
---
- hosts: all
  gather_facts: 'no'
  become: yes
  remote_user: c2s
  become_user: root
            
  tasks:    
  #         - name: Transfer
  #        template: src=/home/vishnu/devops_ansible/script_hub/docker_restart.sh dest=/home/c2s/ansible_script.sh mode=0755

         
         - name: Executing
           script: /home/c2s/find.sh {{ cron }}
           register: shell_result

         - debug:
                 var: shell_result.stdout_lines
