
---
- hosts: all
  gather_facts: 'no'
  become: yes
  remote_user: c2s
  become_user: root
            
         
  # - name: Executing
  #        shell: /home/c2s/cronfind.sh {{ cron }}
  #        register: shell_result

  tasks:
          - name: Cron
            environment:
                    cron: "{{ cron }}"
                    shell: "/home/c2s/cronfind.sh"
                    register: shell_result

                    #         - debug:
                    # var: shell_result.stdout_lines
